version: '3.8'

services:
  jupyter:
    image: jupyter/tensorflow-notebook:x86_64-ubuntu-22.04
    container_name: jupyter_ai_env
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=bcc
    restart: unless-stopped
